### PR TITLE
Clear inspector when no multipart request/response is selected

### PR DESCRIPTION
**Pull request by fgheysels**
- MIME parts are now properly shown in Inspector (previously only the raw contents were displayed, I presume the code in the repository was not up-to-date with the working version of MIME-inspector ?)

- When a request/response is selected in Fiddler that does not contain a multipart content, and the MIME inspector is active, the inspector window is cleared.

- Some code refactorings

### CODE REVIEW

**Comment by samneirinck** [comment]
Super, thanks a lot @fgheysels. Could you take a look at the build failure at https://ci.appveyor.com/project/samneirinck/mimeinspector/build/1.0.22?

**Comment by fgheysels** [comment]
It failed because I've used a C# 7 feature (pattern matching) which is apparently not supported by the build-agent.  Don't know if I can modify the build definition to support C# 7 ?  Otherwise I'll modify the code, but I prefer the former. :)

**Comment by samneirinck** [comment]
Oops, modified the build. Thanks.

**Comment by samneirinck** [comment]
It's in the latest release: https://github.com/samneirinck/MimeInspector/releases/tag/v0.2.0

**Pull request merged**
